In [52]:
import numpy as np

# DataTypes & Attributes

In [53]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [54]:
type(a1)

numpy.ndarray

In [55]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]],
            [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])
# a3 = np.array([[[1, 2, 3],
#               [4, 5, 6]],
#               [[7, 8, 9],
#               [10, 11, 12]],
#              [[13, 14, 15],
#               [16, 17, 18]]])

In [56]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [57]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [58]:
a1.shape

(3,)

In [59]:
a2.shape

(2, 3)

In [60]:
a3.shape

(2, 3, 3)

In [61]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [62]:
a1.ndim

1

In [63]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [64]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [65]:
type(1), type(a2), type(a3)

(int, numpy.ndarray, numpy.ndarray)

In [66]:
#ndarray - very flexible, universal datatype

In [67]:
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [68]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [69]:
sample_array.dtype

dtype('int32')

In [70]:
ones = np.ones((2, 3)) # Shift + TAB returns substring on numpy function 
                 # from the documentation

In [71]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [72]:
ones.dtype

dtype('float64')

In [73]:
type(ones)

numpy.ndarray

In [74]:
zeros = np.zeros((2, 3))

In [75]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [77]:
range_array = np.arange(0, 10, 2)

In [78]:
range_array

array([0, 2, 4, 6, 8])

In [80]:
random_array =np.random.randint(0, 10, size=(3, 5))
random_array

array([[6, 0, 5, 8, 4],
       [3, 8, 2, 9, 6],
       [9, 8, 9, 8, 6]])

In [81]:
random_array.size

15

In [83]:
random_array.shape

(3, 5)

In [84]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.61880567, 0.84428625, 0.21024264],
       [0.69017268, 0.69268236, 0.58694567],
       [0.38920231, 0.81350693, 0.69102366],
       [0.42319211, 0.52064434, 0.60984557],
       [0.21653988, 0.79313596, 0.87963057]])

In [85]:
random_array_2.shape

(5, 3)

In [87]:
random_array_3= np.random.rand(5,3)
random_array_3

array([[0.62333792, 0.87328414, 0.57474127],
       [0.61535847, 0.63087987, 0.39656389],
       [0.22940718, 0.83489005, 0.11854109],
       [0.75648311, 0.84466744, 0.81827178],
       [0.52189845, 0.97161521, 0.93518109]])

In [94]:
# Pseudo-random numbers
np.random.seed(0) # keeps the randomization frozen
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [100]:
np.random.seed(17)
random_array_5 = np.random.random((5, 3))
random_array_5 

array([[0.294665  , 0.53058676, 0.19152079],
       [0.06790036, 0.78698546, 0.65633352],
       [0.6375209 , 0.57560289, 0.03906292],
       [0.3578136 , 0.94568319, 0.06004468],
       [0.8640421 , 0.87729053, 0.05119367]])