In [1]:
#nut butter sales
import numpy as np
import pandas as pd

In [2]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5, 3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [3]:
sales_amount1 = np.random.randint(22, size=(5, 2))
sales_amount1

array([[14, 17],
       [ 5, 13],
       [ 8,  9],
       [20, 19],
       [16, 19]])

In [4]:
# prices array
prices = [10, 8, 12]

In [5]:
weekly_sales = pd.DataFrame(sales_amount,
                           index=["Mon", "Tues", "Wed", "Thur", "Friday"],
                           columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

NameError: name 'sales_amount' is not defined

In [ ]:
# Create prices array
prices = np.array([10, 8, 12])
prices

In [ ]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                            index=["Price"],
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

In [ ]:
prices.shape

In [ ]:
prices

In [ ]:
sales_amount.shape

In [ ]:
total = prices.dot(sales_amounts)

In [ ]:
# Shapes aren't aligned -> Transpose
total_sales = prices.dot(sales_amount.T)
total_sales

In [ ]:
# Create daily_sales
butter_prices

In [ ]:
weekly_sales.shape, butter_prices.shape

In [ ]:
daily_sales = butter_prices.dot(weekly_sales.T)

In [ ]:
weekly_sales.T.shape

In [ ]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

In [ ]:
weekly_sal

In [ ]:
weekly_sales["Total ($)"] = daily_sales.T # Transpose to fit the shape to coloumn
weekly_sales 

### Comparison Operators

In [25]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [26]:
a2 = np.array([[1. , 2. , 3.3],
             [4. , 5. , 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [27]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [28]:
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

In [29]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [30]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [31]:
a1 > 5

array([False, False, False])

In [32]:
a1 < 5

array([ True,  True,  True])

In [33]:
a1 == a1

array([ True,  True,  True])

In [34]:
a1

array([1, 2, 3])

In [35]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

In [36]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

### Sorting array

In [37]:
random_array = np.random.randint(10, size=(3, 5))
random_array

array([[4, 7, 3, 2, 7],
       [2, 0, 0, 4, 5],
       [5, 6, 8, 4, 1]])

In [38]:
np.sort(random_array)

array([[2, 3, 4, 7, 7],
       [0, 0, 2, 4, 5],
       [1, 4, 5, 6, 8]])

In [39]:
np.argsort(random_array)

array([[3, 2, 0, 1, 4],
       [1, 2, 0, 3, 4],
       [4, 3, 0, 1, 2]], dtype=int64)

In [40]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [41]:
np.argmin(a1)

0

In [42]:
np.argmax(a1)

2

In [43]:
random_array

array([[4, 7, 3, 2, 7],
       [2, 0, 0, 4, 5],
       [5, 6, 8, 4, 1]])

In [44]:
np.argmax(random_array, axis=0)

array([2, 0, 2, 1, 0], dtype=int64)

In [45]:
np.argmax(random_array, axis=1)

array([1, 4, 2], dtype=int64)

In [48]:
np.argmax(random_array, axis=1)

array([1, 4, 2], dtype=int64)