In [56]:
#nut butter sales
import numpy as np
import pandas as pd

In [57]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5, 3))
sales_amounts


array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [58]:
sales_amount1 = np.random.randint(22, size=(5, 2))
sales_amount1

array([[14, 17],
       [ 5, 13],
       [ 8,  9],
       [20, 19],
       [16, 19]])

In [59]:
# prices array
prices = [10, 8, 12]

In [60]:
weekly_sales = pd.DataFrame(sales_amount,
                           index=["Mon", "Tues", "Wed", "Thur", "Friday"],
                           columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon                12             15              0
Tues                3              3              7
Wed                 9             19             18
Thur                4              6             12
Friday              1              6              7

In [61]:
# Create prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [62]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                            index=["Price"],
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [63]:
prices.shape

(3,)

In [64]:
prices

array([10,  8, 12])

In [65]:
sales_amount.shape

(5, 3)

In [66]:
total = prices.dot(sales_amounts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [67]:
# Shapes aren't aligned -> Transpose
total_sales = prices.dot(sales_amount.T)
total_sales

array([240, 138, 458, 232, 142])

In [68]:
# Create daily_sales
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [71]:
weekly_sales.shape, butter_prices.shape

((5, 3), (1, 3))

In [72]:
daily_sales = butter_prices.dot(weekly_sales.T)

In [73]:
weekly_sales.T.shape

(3, 5)

In [75]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thur  Friday
Price  240   138  458   232     142

In [76]:
weekly_sal

Almond butter  Peanut butter  Cashew butter
Mon                12             15              0
Tues                3              3              7
Wed                 9             19             18
Thur                4              6             12
Friday              1              6              7

In [79]:
weekly_sales["Total ($)"] = daily_sales.T # Transpose to fit the shape to coloumn
weekly_sales 

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon                12             15              0        240
Tues                3              3              7        138
Wed                 9             19             18        458
Thur                4              6             12        232
Friday              1              6              7        142

### Comparison Operators

In [80]:
a1 = np.array

NameError: name 'a1' is not defined