## Introduction to Scikit-Learn(sklearn)
### Supervised Learning

This notebook demonstrates some of the most common Scikit-Learn functions.

List of contents:

In [1]:
covering = [
    "0. An end-to-end Scikit-Learn workflow",
    "1. Getting the data ready",
    "2. Choose the right estimator/algorithm for our problems",
    "3. Fit the model/algorithm and use it to make predicttions on our data",
    "4. Evaluating a model",
    "5. Improve a model",
    "6. Save and load a trained model",
    "7. Putting it all together!"
]

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
covering

['0. An end-to-end Scikit-Learn workflow',
 '1. Getting the data ready',
 '2. Choose the right estimator/algorithm for our problems',
 '3. Fit the model/algorithm and use it to make predicttions on our data',
 '4. Evaluating a model',
 '5. Improve a model',
 '6. Save and load a trained model',
 '7. Putting it all together!']

## 0. An end-to-end Scikit-Learn workflow

In [4]:
# 1. Get the data ready
import pandas as pd
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [5]:
# Create X (features matrix)
X = heart_disease.drop("target", axis=1)

# Create y(labels)
y = heart_disease["target"]

In [6]:
# 2. Choose the right model and hyperparamaters (This case is classification)
from sklearn.ensemble import RandomForestClassifier
cls = RandomForestClassifier()

# We'll keep the default hyperparamaters
cls.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [7]:
# 3. Fit the model to the training data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [8]:
cls.fit(X_train, y_train)

RandomForestClassifier()

In [9]:
# make a prediction
y_preds = cls.predict(X_test)
y_preds

array([1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1], dtype=int64)

In [10]:
y_test

129    1
215    0
258    0
200    0
287    0
      ..
246    0
193    0
300    0
265    0
8      1
Name: target, Length: 61, dtype: int64

In [11]:
#4. Evaluate the model on the training data and test data
cls.score(X_train, y_train)

1.0

In [12]:
cls.score(X_test, y_test)

0.819672131147541

In [13]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.87      0.79      0.83        33
           1       0.77      0.86      0.81        28

    accuracy                           0.82        61
   macro avg       0.82      0.82      0.82        61
weighted avg       0.82      0.82      0.82        61



In [14]:
accuracy_score(y_test, y_preds)

0.819672131147541

In [15]:
# 5. Improve a models
# Try different amount of n_esitmators
np.random.seed(17)
for i in range(10, 100, 10):
    print(f"Trying models with {i} estimators...")
    cls = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy on test set: {cls.score(X_test, y_test) * 100}:.2f")
    print("")

Trying models with 10 estimators...
Model accuracy on test set: 78.68852459016394:.2f

Trying models with 20 estimators...
Model accuracy on test set: 81.9672131147541:.2f

Trying models with 30 estimators...
Model accuracy on test set: 81.9672131147541:.2f

Trying models with 40 estimators...
Model accuracy on test set: 81.9672131147541:.2f

Trying models with 50 estimators...
Model accuracy on test set: 83.60655737704919:.2f

Trying models with 60 estimators...
Model accuracy on test set: 78.68852459016394:.2f

Trying models with 70 estimators...
Model accuracy on test set: 85.24590163934425:.2f

Trying models with 80 estimators...
Model accuracy on test set: 78.68852459016394:.2f

Trying models with 90 estimators...
Model accuracy on test set: 85.24590163934425:.2f



In [16]:
# 6. Save a model and load it
import pickle

pickle.dump(cls, open("random_forest_model1.pkl", "wb"))

In [17]:
loaded_model = pickle.load(open("random_forest_model1.pkl", "rb"))
loaded_model.score(X_test, y_test)

0.8524590163934426

## 1. Getting our data ready to be used with machine learning

Three main things we have to do:

    1. Split the data into features and labels(usually `X` & `y`)
    2. Filling (also called imputing) or disregarding missing values
    3. Converting non-numerical values to numerical values
        (also called feature encoding)

In [18]:
# Step 1.
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [19]:
X = heart_disease.drop("target", axis=1)
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [20]:
y = heart_disease["target"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [21]:
# Fundamental principle - never evaluate or test the models on the data that 
# it has learned from -> hence we split it training and test sets

In [22]:
# Split the data into training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [23]:
X_train.shape, X_test.shape, y_train.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (242,), (61,))

In [24]:
X.shape[0] * 0.8

242.4

In [25]:
len(heart_disease)

303

# Step 2.
## Make sure it's all numerical

In [26]:
car_sales = pd.read_csv("car-sales-extended.csv")
len(car_sales)

1000

In [27]:
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [28]:
car_sales["Doors"].value_counts()

Doors
4    856
5     79
3     65
Name: count, dtype: int64

In [29]:
# Split the data in the X and Y
X = car_sales.drop("Price", axis=1)
y = car_sales["Price"]

# Split into training and test
X_train, X_test, y_trian, y_test = train_test_split(X,
                                                   y,
                                                   test_size=0.2)

In [30]:
# Build machine learning model
from sklearn.ensemble import RandomForestRegressor # predicts a number
model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)
# as of current stat the model can't deal with strings

ValueError: could not convert string to float: 'Nissan'

In [ ]:
# Transforming string to Numbers
# Turn categories to Numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_fetures = ["Make", "Colour", "Doors"]

one_hot = OneHotEncoder() # transforms data to the numbers
transformer = ColumnTransformer([("one_hot",
                                 one_hot,
                                 categorical_fetures)],
                               remainder="passthrough")
transformed_X = transformer.fit_transform(X)
transformed_X

In [ ]:
pd.DataFrame(transformed_X)

In [ ]:
X.head()

In [ ]:
dummies = pd.get_dummies(car_sales[["Make", "Colour", "Doors"]])
dummies

In [ ]:
# Refit the model
np.random.seed(17)
X_train, X_test, y_train, y_test = train_test_split(transformed_X,
                                                   y,
                                                   test_size=0.2)

model.fit(X_train, y_train)

In [ ]:
X.head()

In [ ]:
model.score(X_test, y_test)

### Handling missing values

1. Fill them with some value(aka. imputation).
2. Remove the samples with missing data altogether.

In [ ]:
# Import car sales missing data
car_sales_missing = pd.read_csv("car-sales-extended-missing-data.csv")
car_sales_missing

In [ ]:
car_sales_missing.isna().sum()

In [ ]:
# Create X/Y
X = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]


In [ ]:
# Transforming string to Numbers
# Turn categories to Numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_fetures = ["Make", "Colour", "Doors"]

one_hot = OneHotEncoder() # transforms data to the numbers
transformer = ColumnTransformer([("one_hot",
                                 one_hot,
                                 categorical_fetures)],
                               remainder="passthrough")
transformed_X = transformer.fit_transform(X)
transformed_X

In [ ]:
car_sales_missing

## Option 1: Fill missing data with Pandas

In [ ]:
# Fill the "Make" column
car_sales_missing["Make"].fillna("missing", inplace=True)

#Fill the "Colour"
car_sales_missing["Colour"].fillna("missing", inplace=True)

#Fill the "Odometer (KM)"
car_sales_missing["Odometer (KM)"].fillna(car_sales_missing["Odometer (KM)"].mean(), inplace=True)

# Fill the "Doors" 
car_sales_missing["Doors"].fillna(4, inplace=True)

In [ ]:
car_sales_missing.isna().sum()

In [ ]:
# Remove rows with missing Price value
car_sales_missing.dropna(inplace=True)

In [ ]:
len(car_sales_missing)

In [ ]:
X = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

In [ ]:
# Transforming string to Numbers
# Turn categories to Numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_fetures = ["Make", "Colour", "Doors"]

one_hot = OneHotEncoder() # transforms data to the numbers
transformer = ColumnTransformer([("one_hot",
                                 one_hot,
                                 categorical_fetures)],
                               remainder="passthrough")
transformed_X = transformer.fit_transform(car_sales_missing)
transformed_X

## Option 2: Fill missing values with Scikit-learn

In [ ]:
car_sales_missing = pd.read_csv("car-sales-extended-missing-data.csv")

In [ ]:
car_sales_missing.head()

In [ ]:
car_sales_missing.isna().sum()

In [ ]:
# Drop price with no vlaues
car_sales_missing.dropna(subset=["Price"], inplace=True)
car_sales_missing.isna().sum()

In [ ]:
# Split into X & y
X = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

In [ ]:
# Fill missing values with Scikit-Learn
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Fill categorical values with 'missing' & numerical values with mean
cat_imputer = SimpleImputer(strategy="constant", fill_value="missing")
door_imputer = SimpleImputer(strategy="constant", fill_value=4)
num_imputer = SimpleImputer(strategy="mean")

# Define columns
cat_features = ["Make", "Colour"]
door_features = ["Doors"]
num_features = ["Odometer (KM)"]

# Create an imputer (something that fills missing data)
imputer = ColumnTransformer ([
    ("cat_imputer", cat_imputer, cat_features),
    ("door_imputer", door_imputer, door_features),
    ("num_imputer", num_imputer, num_features)
])

# Transform the data
filled_X = imputer.fit_transform(X)
filled_X

In [ ]:
car_sales_filled = pd.DataFrame(filled_X,
                               columns=["Make", "Colour", "Doors", "Odometer (KM)"])

In [ ]:
car_salles_filled.head()

In [ ]:
car_sales_filled.isna().sum()

In [ ]:
# Transforming string to Numbers
# Turn categories to Numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_fetures = ["Make", "Colour", "Doors"]

one_hot = OneHotEncoder() # transforms data to the numbers
transformer = ColumnTransformer([("one_hot",
                                 one_hot,
                                 categorical_fetures)],
                               remainder="passthrough")
transformed_X = transformer.fit_transform(car_sales_filled)
transformed_X

In [ ]:
# Now we've got the data as numbers (no NaN)
# Let's fit the model
np.random.seed(17)
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(transformed_X,
                                                   y,
                                                   test_size=0.2)

model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

In [ ]:
# Comparing the models
len(car_sales_filled), len(car_sales)

### Note
#### Feature engineering/Feature encoding - the process of turning the non numerical to numerical
#### Imputing - filling the missing data

In [ ]:
covering

## 2. Choosing the right estimator/algorith for the problem

Notes:
    
* Sklearn refers to machine learning models, algorithm as estimators.
* Classification problem - predicting a category (heart disease or not)
    * Sometimes you'll see `cls` (short for classifier) user as a classification estimator.
* Regression problem - predicting a number (selling price of a car)

### Choosing the right estimator map

https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

### 2.1 Picking a machine learning model for regression
Toy datasets from scikit learn:
https://scikit-learn.org/stable/datasets/toy_dataset.html

California Housing dataset.

In [ ]:
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()

In [ ]:
housing

In [ ]:
housing_df = pd.DataFrame(housing["data"], columns=housing["feature_names"])

In [ ]:
housing_df["target"] = housing["target"]
housing_df

In [ ]:
# hosuing_df = housing_df.drop("MedHouseVal", axis=1, inplace=True) # doesn't work without inplace
housing_df.drop("target", axis=1)

In [ ]:
housing_df

### Ridge model

In [ ]:
# Improt algorithm/estimator
from sklearn.linear_model import Ridge

# Setup random see
np.random.seed(17)

# Create the data
X = housing_df.drop("target", axis=1)
y = housing_df["target"] # median house price in $100,000s

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instantiate and fit the model ( on the training set)
model = Ridge()
model.fit(X_train, y_train)

# Check the score of the model (on the test set)
model.score(X_test, y_test)

In [ ]:
<img src="Models/ml_map.png" alt="ML Map">

In [ ]:
covering

## Ensemble technique

A techinque applied in machine learning where machin learning model is created of n amount of smaller models.

Powerful model based on Decision Trees.
Famous

Chosoing and ensemble model: https://scikit-learn.org/stable/modules/ensemble.html

### RandomForestRegrressor model

In [ ]:
# RandomForestRegressor
from sklearn.ensemble import RandomForestRegressor

# Settup random seed
np.random.seed(42)

X = housing_df.drop("target", axis=1)
y = housing_df["target"]

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

#Create random forest model
model = RandomForestRegressor()
model.fit(X_train, y_train)

# Eval
model.score(X_test, y_test)

### 2.2 Choosing an estimator for a classification problem

In [ ]:
heart_disease = pd.read_csv("heart-disease.csv")
# heart_disease = heart_disease.drop(heart_disease.index[-1])

In [ ]:
missing_values_count = heart_disease.isna().sum()
missing_values_count

In [ ]:
len(heart_disease)

Lineral Clasification `LinearSVC`

In [ ]:
# Import the LinearSVC
from sklearn.svm import LinearSVC

# Setup seed
np.random.seed(42)

# Load the data
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Instantiate LinearSVC
clf = LinearSVC(max_iter=1000)
clf.fit(X_train, y_train)

# Evaluate the LinearSCV
clf.score(X_test, y_test)

In [ ]:
heart_disease["target"].value_counts()

### Random Forest Classifier

In [ ]:
# Import the estimator
from sklearn.ensemble import RandomForestClassifier

# Setup seed
np.random.seed(42)

# Load the data
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Instantiate RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train, y_train)

# Evaluate RandomForestClassifier
clf.score(X_test, y_test)

Tidbit:
    If you have structured data, use ensabmle methods
    IF you have unstrutured data, use deep learning or transfer learning

In [ ]:
covering

In [ ]:
## 3. Fit the model/algorithm on our data and use it to make predictions

### 3.1 Fitting the model to the data

X = features, featur variables,


In [ ]:
# Import the estimator
from sklearn.ensemble import RandomForestClassifier

# Setup seed
np.random.seed(42)

# Load the data
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Instantiate RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)

# Fit the model to the data (training the model the data)
clf.fit(X_train, y_train)


# Evaluate RandomForestClassifier
clf.score(X_test, y_test)

### 3.2 Make predictions using a machine learnign model

2 ways to make predictions
1. predict() - predicts accuracy
2. predict_proba - predicts probability

In [ ]:
# Use a trained model to make predictions
# clf.predict(np.array([1, 7, 8, 3, 4])) # this doesn't work

In [ ]:
clf.predict(X_test)

In [ ]:
np.array(y_test)

In [ ]:
# Compare predictions to truth labels to evaluate the model
y_preds = clf.predict(X_test)
np.mean(y_preds == y_test)

In [ ]:
clf.score(X_test, y_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_preds)

Make predictions with `predict_proba()`


In [ ]:
# predict_proba() returns probabilities of a classification label
clf.predict_proba(X_test[:5])

In [ ]:
# compare with predict()
clf.predict(X_test[:5])

In [ ]:
    X_test[:5]

`predict()` can also be used on regression models.

In [ ]:
housing_df.head()

In [ ]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

# Load
X = housing_df.drop("target", axis=1)
y = housing_df["target"]

#Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Create model instance
model = RandomForestRegressor()

# Fit the model
model.fit(X_train, y_train)

# Predictions
y_preds = model.predict(X_test)

In [31]:
y_preds[:10]

array([1, 0, 0, 1, 1, 0, 1, 0, 0, 0], dtype=int64)

In [32]:
np.array(y_test[:10])

array([18310,  6391, 10429, 22505, 10855, 10494, 29140,  4566, 13519,
        4034], dtype=int64)

In [33]:
# Compare the predictions to the truth
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)

ValueError: Found input variables with inconsistent numbers of samples: [200, 61]

In [ ]:
housing_df["target"]

In [ ]:
covering

# 4. Evaluating a machine learning model

Three ways to evaluate Scikit-Learng models/estimators:

    1. Estimator's built in `score()` method
    2. The `scoring` parameter
    3. Problem-specific metric functions.
    
Documentation: https://scikit-learn.org/stable/modules/model_evaluation.html

## 4.1 Evaluating a model with `score` method

In [ ]:
# Import the estimator
from sklearn.ensemble import RandomForestClassifier

# Setup seed
np.random.seed(42)

# Load the data
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Instantiate RandomForestClassifier
clf = RandomForestClassifier(n_estimators=1000)

# Fit the model to the data (training the model the data)
clf.fit(X_train, y_train)

# Evaluate RandomForestClassifier
clf.score(X_test, y_test)

In [ ]:
# the highest value for the .score() methods is 1.0, the lowest is 0.0
clf.score(X_train, y_train)

In [ ]:
clf.score(X_test, y_test)

In [ ]:
hosuing_df = pd.read_csv("heart-disease.csv")

In [ ]:
# RandomForestRegressor
from sklearn.ensemble import RandomForestRegressor

# Settup random seed
np.random.seed(42)

X = housing_df.drop("target", axis=1)
y = housing_df["target"]

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

#Create random forest model
model = RandomForestRegressor(n_estimators=10)

#Fit - create model isntance
model.fit(X_train, y_train)

# Eval
model.score(X_test, y_test)

In [ ]:
# The default score() evaluation metric is r_squared for regression algorithms
# Highet = 1.0, lowest = 0.0
model.score(X_test, y_test)

In [36]:
## 4.2 Evaluating a model using hte `scoring` paramater
from sklearn.model_selection import cross_val_score

from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

clf = RandomForestClassifier(n_estimators=100)

clf.fit(X_train, y_train);

In [37]:
clf.score(X_test, y_test)

0.8524590163934426

In [38]:
cross_val_score(clf, X, y)

array([0.81967213, 0.86885246, 0.81967213, 0.78333333, 0.76666667])

#### Cross validation creates 5 different models using 100% of the dataset for training end testing, splitting it into N amount of training/test splits

### 4.2. Evaluating the model using the `scoring` parameter

In [39]:
from sklearn.model_selection import cross_val_score

from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

clf = RandomForestClassifier(n_estimators=100)

clf.fit(X_train, y_train);

In [40]:
clf.score(X_test, y_test)

0.8524590163934426

In [44]:
cross_val_score(clf, X, y)

array([0.85245902, 0.8852459 , 0.81967213, 0.8       , 0.78333333])

In [43]:
cross_val_score(clf, X, y, cv=10)

array([0.90322581, 0.80645161, 0.87096774, 0.9       , 0.86666667,
       0.8       , 0.73333333, 0.86666667, 0.73333333, 0.8       ])

In [49]:
np.random.seed(42)

# Single training and test split score
single_score = clf.score(X_test, y_test)

#Take the mean of 5-fold cross-validation score

clf_cross_val_score = np.mean(cross_val_score(clf, X, y, cv=5))

#Compare the two
single_score, clf_cross_val_score

(0.8524590163934426, 0.8248087431693989)

In [ ]:
# Default scoring paramater of classifier = mean accuracy
clf.score()

In [50]:
# Scoring parameter set to None by default
cross_val_score(clf, X, y, cv=5, scoring=None)

array([0.78688525, 0.86885246, 0.80327869, 0.78333333, 0.76666667])